CREATE TABLE PAYMENT_TYPES (
	ID INT PRIMARY KEY IDENTITY,
	TYPE NVARCHAR(25) NOT NULL
	);

CREATE TABLE SHIPPING_TYPES (
	ID INT PRIMARY KEY IDENTITY,
	TYPE NVARCHAR(25) NOT NULL
	);

CREATE TABLE CATEGORIES (
	ID INT PRIMARY KEY IDENTITY,
	NAME NVARCHAR(30) NOT NULL,
	DESCRIPTION NVARCHAR(MAX) NOT NULL
	);

CREATE TABLE ITEMS (
	ID INT PRIMARY KEY IDENTITY,
	CATEGORY_ID INT REFERENCES CATEGORIES(ID),
	PRICE_WITH_SALE MONEY NOT NULL,
	PRICE_WITHOUT_SALE MONEY,
	QUANTITY INT NOT NULL,
	CODE NVARCHAR(20) NOT NULL
	);

CREATE TABLE CLIENTS (
	ID INT PRIMARY KEY IDENTITY,
	TELEPHONE_NUMBER NVARCHAR(16) NOT NULL,
	EXTRA_TELEPHONE_NUMBER NVARCHAR(16),
	FIRST_NAME NVARCHAR(30) NOT NULL,
	SECOND_NAME NVARCHAR(30) NOT NULL,
	THIRD_NAME NVARCHAR(30),
	EMAIL NVARCHAR(255) NOT NULL,
	BIRTHDAY DATETIME NOT NULL,
	CITY NVARCHAR(25) NOT NULL,
	KIDS_QUANTITY INT NOT NULL,
	COUNTRY NVARCHAR(25) NOT NULL
	);

	CREATE TABLE SHIPPING_ADDRESSES(
		ID INT PRIMARY KEY IDENTITY,
		REGION NVARCHAR(30) NOT NULL,
		CITY NVARCHAR(30) NOT NULL,
		DISTRICT NVARCHAR(30) NOT NULL,
		HOUSE_NUMBER NVARCHAR(30) NOT NULL,
		APARTAMENT_NUMBER NVARCHAR(30)
		);




	CREATE TABLE ORDERS (
		ID INT PRIMARY KEY IDENTITY,
		PAYMENT_TYPE_ID INT REFERENCES PAYMENT_TYPES(ID) NOT NULL,
		SHIPPING_TYPE_ID INT REFERENCES SHIPPING_TYPES(ID) NOT NULL,
		SHIPPING_ADDRESS_ID INT REFERENCES SHIPPING_ADDRESSES(ID) NOT NULL,
		TOTAL_PRICE MONEY NOT NULL,
		IS_SHIPPED BIT NOT NULL
		);

CREATE TABLE ORDER_PRODUCTS (
	ID INT PRIMARY KEY IDENTITY,
	ORDER_ID INT REFERENCES ORDERS(ID),
	ITEM_ID INT REFERENCES ITEMS(ID),
	PRICE_WITH_SALE MONEY NOT NULL,
	PRICE_WITHOUT_SALE MONEY NOT NULL,
	ITEM_QUANTITY INT NOT NULL
	);

	ALTER TABLE SHIPPING_ADDRESSES
ADD STREET NVARCHAR(25)

ALTER TABLE ORDERS 
ADD CLIENT_ID INT 

ALTER TABLE ORDERS
ADD FOREIGN KEY(CLIENT_ID) REFERENCES CLIENTS(Id); 
 
 ALTER TABLE ORDERS
 ALTER COLUMN CLIENT_ID INT NOT NULL

 ALTER TABLE ITEMS
 ADD NAME NVARCHAR(25)
