CREATE PROCEDURE CLIENTS_FROM_ODESSA AS
SELECT * FROM CLIENTS
WHERE CITY = 'Odessa'

EXEC CLIENTS_FROM_ODESSA

CREATE TRIGGER ORDERPRODUCTS_INSERT
ON ORDER_PRODUCTS
AFTER INSERT
AS 
UPDATE ITEMS
SET QUANTITY = QUANTITY - (SELECT ITEM_QUANTITY FROM inserted)
WHERE ID = (SELECT ITEM_ID FROM inserted)

DROP TRIGGER ORDERPRODUCTS_INSERT


CREATE FUNCTION PRODUCT_SALE_COUNT  (@itemId INT)
RETURNS INT
BEGIN
DECLARE @percent INT
DECLARE @max_price MONEY
DECLARE @min_price MONEY
  SET @min_price = (SELECT PRICE_WITH_SALE FROM ITEMS WHERE ID = @itemId)
  SET @max_price = (SELECT PRICE_WITHOUT_SALE FROM ITEMS WHERE ID = @itemId)  
  SET @percent = (100-(@min_price/@max_price)*100) ;
  RETURN @percent
END


SELECT [dbo].PRODUCT_SALE_COUNT(1002);